### PR TITLE
Remove React & React DOM from dev dependencies

### PR DESCRIPTION
**Pull request by harryadel**
Give it another go? @timvansteenis

### CODE REVIEW

**Comment by timvansteenis** [comment]
@harryadel thanks for the attempt but no effect. React gets loaded twice. Pretty sure this is because the `package-a` is linked and contains react `package-a/node-modules/react` while the application also install that same depedency `myapp/node_modules/react`.

Could be similar to this issue https://github.com/meteor/meteor/issues/11030

**Comment by harryadel** [comment]
Sorry for dipping. But there doesn't seem to be any problems when I run the app
react

Just in case, but can you remove your node_modules and reinstall? that might help.

**Comment by timvansteenis** [comment]
@harryadel I think you are on the wrong branch. Can you check the main branch? 

You should see another text: https://github.com/lessonup/meteor-monorepo-issue/blob/main/packages/package-a/src/feature/MyFeature.tsx#L24

**Comment by harryadel** [comment]
You're right something was off with my setup; I was on the right branch but I had to reinstall my node_modules. Anyways, I think importing react as a peer dependency did the trick. Let me know how it goes.  

react-peer-issue

**Comment by timvansteenis** [comment]
Hi @harryadel , sorry for my late reply. Was on holiday.

This works indeed! Which is nice. Thanks for that and all the effect you have put it helping us.

**Pull request merged**
